### ISSUE TITLE
Are there timers / setTimeout() or access to millis()?

### ISSUE THREAD

**Issue by cottsak** [cesanta/smart.js#53]
More doco somewhere?

**Comment by mmikulicic** [comment]
We aim at implementing a reasonable subset of the ecmascript standard.

Thus we have:

- `new Date().getTime()`
- and `setTimeout()`

Unfortunately we didn't yet document which parts of it are implemented and which not, mostly because we are still in alpha and hopefully we could just defer to sources as MDN for reference documentation of the JS standard library. 

We did however document our C<->JS API and any non standard JS API.

Anyway, I guess it would make sense to extract the list of supported functions from our sources somehow.

**Comment by cottsak** [comment]
Great news. 

`setInterval()` too then I assume?

**Comment by mmikulicic** [comment]
Unfortunately that one is not in yet, but it should be.
